# analyze data

In [20]:
import polars as pl
import seaborn as sns

In [2]:
data = pl.read_csv('data/smartphone_battery_features.csv')
data.head()

shape: (5, 15)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Device_ID ┆ device_ag ┆ battery_c ┆ avg_scree ┆ … ┆ signal_st ┆ charging_ ┆ usage_int ┆ thermal_ │
│ ---       ┆ e_months  ┆ apacity_m ┆ n_on_hour ┆   ┆ rength_av ┆ habit_sco ┆ ensity_sc ┆ stress_i │
│ str       ┆ ---       ┆ ah        ┆ s_per_day ┆   ┆ g         ┆ re        ┆ ore       ┆ ndex     │
│           ┆ i64       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆           ┆ i64       ┆ f64       ┆   ┆ str       ┆ i64       ┆ f64       ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 207dd94c- ┆ 38        ┆ 4500      ┆ 7.1       ┆ … ┆ Poor      ┆ 4         ┆ 10.0      ┆ 4.04     │
│ 0430-43aa ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ -b388-489 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 344…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 3f4d1d33- ┆ 28        ┆ 3000      ┆ 6.8       ┆ … ┆ Good      ┆ 7         ┆ 10.0      ┆ 4.23     │
│ ba89-4814 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ -a168-7b4 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ cc7…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ b4adca05- ┆ 14        ┆ 3000      ┆ 7.2       ┆ … ┆ Good      ┆ 6         ┆ 10.0      ┆ 2.21     │
│ 564f-4b70 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ -ab69-e8d ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 66e…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4147e039- ┆ 42        ┆ 3000      ┆ 5.5       ┆ … ┆ Good      ┆ 8         ┆ 10.0      ┆ 3.13     │
│ 31b7-480a ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ -bbc9-03c ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ d0f…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 3f9b0fb7- ┆ 7         ┆ 3000      ┆ 7.6       ┆ … ┆ Good      ┆ 5         ┆ 10.0      ┆ 4.95     │
│ 73c2-4ab7 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ -8e30-7b4 ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 920…      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## targets

In [3]:
targets = pl.read_csv('data/smartphone_battery_targets.csv')
targets.head()

shape: (5, 3)
┌─────────────────────────────────┬────────────────────────────────┬────────────────────┐
│ Device_ID                       ┆ current_battery_health_percent ┆ recommended_action │
│ ---                             ┆ ---                            ┆ ---                │
│ str                             ┆ f64                            ┆ str                │
╞═════════════════════════════════╪════════════════════════════════╪════════════════════╡
│ 207dd94c-0430-43aa-b388-489344… ┆ 32.8                           ┆ Change Phone       │
│ 3f4d1d33-ba89-4814-a168-7b4cc7… ┆ 50.3                           ┆ Replace Battery    │
│ b4adca05-564f-4b70-ab69-e8d66e… ┆ 66.1                           ┆ Replace Battery    │
│ 4147e039-31b7-480a-bbc9-03cd0f… ┆ 46.8                           ┆ Change Phone       │
│ 3f9b0fb7-73c2-4ab7-8e30-7b4920… ┆ 67.2                           ┆ Replace Battery    │
└─────────────────────────────────┴────────────────────────────────┴────────────────────┘

#### target distribution

In [5]:
targets['recommended_action'].unique()

shape: (3,)
Series: 'recommended_action' [str]
[
	"Change Phone"
	"Replace Battery"
	"Keep Using"
]

In [21]:
targets_distributions = targets.group_by('recommended_action').agg(
    pl.col('current_battery_health_percent').max().alias('max_health_percentage'),
    pl.col('current_battery_health_percent').min().alias('min_health_percentage'),
    pl.col('current_battery_health_percent').mean().round(2).alias('mean_health_percentage'),
    pl.col('current_battery_health_percent').count().alias('count')
    )

targets_distributions

shape: (3, 5)
┌────────────────────┬───────────────────────┬──────────────────────┬──────────────────────┬───────┐
│ recommended_action ┆ max_health_percentage ┆ min_health_percentag ┆ mean_health_percenta ┆ count │
│ ---                ┆ ---                   ┆ e                    ┆ ge                   ┆ ---   │
│ str                ┆ f64                   ┆ ---                  ┆ ---                  ┆ u32   │
│                    ┆                       ┆ f64                  ┆ f64                  ┆       │
╞════════════════════╪═══════════════════════╪══════════════════════╪══════════════════════╪═══════╡
│ Replace Battery    ┆ 74.9                  ┆ 50.0                 ┆ 62.94                ┆ 2325  │
│ Change Phone       ┆ 49.9                  ┆ 10.0                 ┆ 38.37                ┆ 1235  │
│ Keep Using         ┆ 100.0                 ┆ 75.0                 ┆ 82.81                ┆ 1440  │
└────────────────────┴───────────────────────┴──────────────────────┴──────────────────────┴───────┘